### PR TITLE
[django] Add support for django 2.2 #108

### PR DESCRIPTION
**Pull request by EdgeKing810**
Let me know if there's anything more to be done for this PR.

I'll look at the contributor's board and try to find tasks that I can attempt to learn and do.

### CODE REVIEW

**Comment by EdgeKing810** [comment]
Tests will pass after https://github.com/openwisp/django-x509/pull/61 is merged.

**Comment by nemesisdesign** [comment]
Restarted https://travis-ci.org/openwisp/django-netjsonconfig/jobs/534192102

**Comment by nemesisdesign** [comment]
Putting it up as a GCI task.

**Comment by IAmAMissingColon** [comment]
Hello ! @nemesisdesign I have added Django2.2 support in my PR becuase Django3 was causing some dependencies not to work properly.. So what should I do?

**Pull request closed without merging**
