### PR TITLE
Extract jsonschema-widget to separate package

### LINKED ISSUE #94: [admin] Extract jsonschema-widget to separate django package
This task is happening here: https://github.com/openwisp/django-jsonschema-widget/pull/1

Once the first version of the widget is ready we can remove the code of the widget from here and import that one.

This will help us to reuse this widget more easily across other django modules.

### PR DESCRIPTION
**Pull request by atb00ker**
Extract jsonschema-widget to separate django package: github.com/openwisp/django-jsonschema-widget

**Status:** Dependent on https://github.com/openwisp/django-jsonschema-widget/pull/3
 
Closes #94

### CODE REVIEW

**Comment by auvipy** [comment]
thanks for pulling it here!

**Comment by nemesisdesign** [comment]
@atb00ker great :-)

**Comment by atb00ker** [comment]
@auvipy, thanks looks like it's all working now.
I'll add the testcase asap.  :)

**Comment by auvipy** [comment]
cool!

**Comment by nemesisdesign** [comment]
Closing as won't fix for now.

**Pull request closed without merging**
