### PR TITLE
Issue/95

### PR DESCRIPTION
**Pull request by NoumbissiValere**
added Logic to import templates.
Fixes #95

### CODE REVIEW

**Comment by NoumbissiValere** [comment]
@nemesisdesign Please can you review this when you have time? thanks

**Comment by dwang** [comment]
Just a minor thing, to fix the Travis error, you can just run `isort --recursive .` and it will automatically sort the incorrect imports for you.

**Comment by NoumbissiValere** [comment]
Thanks @dwang for spotting this out.. will adjust it

**Comment by NoumbissiValere** [comment]
@dwang i think it is now waiting for review after the merge of https://github.com/openwisp/django-netjsonconfig/pull/122, so that i can rebase and push again.

**Pull request merged**
