### PR TITLE
[x509] VPN files have 0600 permissions by default #169

### LINKED ISSUE #169: [x509] VPN client files should be created with 0600 permissions by default.
VPN client files (ca, cert, key) should be created with 0600 permissions by default.

### PR DESCRIPTION
**Pull request by TheOneAboveAllTitan**
Set default permission of files to 0600 and modified tests accordingly.
Minor fix in tests/settings.py
Closes #169
Applies changes from https://github.com/openwisp/netjsonconfig/pull/148/

ezgif com-video-to-gif (1)

### CODE REVIEW

**Comment by TheOneAboveAllTitan** [comment]
The build is failing due to unreleased changes from https://github.com/openwisp/netjsonconfig/pull/148
I installed `netjsonconfig` using git, and all tests were passed.

**Comment by atb00ker** [comment]
Hey did you check the testcases / travis.
And I think we should do some manual testing for this one when it's ready, did you test it? :smile:

**Comment by TheOneAboveAllTitan** [comment]
I installed `netjsonconfig` using `pip install https://github.com/openwisp/netjsonconfig/tarball/master
` and the updated tests passed on my machine. I added the GIF to show that changes in UI are also reflected as suggested by @nemesisdesign https://github.com/openwisp/django-netjsonconfig/issues/169#issuecomment-605464177 :smile:

**Comment by nemesisdesign** [comment]
PS: will do that asap. Started doing it but getting late here so will resume tomorrow hopefully.

**Comment by nemesisdesign** [comment]
Thanks! :+1:

**Pull request merged**
